### ISSUE TITLE
doesn't work on elm 0.18

### ISSUE THREAD

**Issue by oli-obk** [mukeshsoni/elm-instant#12]
the version requirements of the template is < 0.18

**Comment by mukeshsoni** [comment]
yeah, don't have a good solution for this at the moment. I have a couple of ways in mind to handle this - 
1. Automatically detect elm version and install packages accordingly
2. Allow commands to switch between elm versions
3. Allow commands to install either 0.17 or 0.18 version packages

Will think about it a little more

**Comment by brunetton** [comment]
Apparently @shamansir in his fork fixed it ?
https://github.com/shamansir/elm-instant/commit/44d69bfdd26eb2a570584bfef68c44521c75b265

Should be amazing if he could open a PR

**Comment by mukeshsoni** [comment]
@shamansir did you?

**Comment by shamansir** [comment]
@mukeshsoni I did, but my fork is a bit different now, so it's better just to copy-paste changes or cherry-pick this commit from my repo.

**Comment by shamansir** [comment]
I'll do it :)

**Comment by shamansir** [comment]
@mukeshsoni 

> 1. Automatically detect elm version and install packages accordingly

Regarding this point, @rtfeldman introduced https://github.com/rtfeldman/elm-use today, and it could be used to switch versions easily.

![Demo](https://cloud.githubusercontent.com/assets/1094080/21740236/4d59430a-d468-11e6-85c6-9f2e1c9ec638.gif)

**Comment by mukeshsoni** [comment]
@shamansir Will take a look. Thanks! 

Actually have been away from looking at anything outside office work for quite some time now.

**Comment by brunetton** [comment]
Thanks!

**Comment by mukeshsoni** [comment]
i couldn't get @shamansir PR to work properly (doesn't work after changing the open file once). Reopening this issue. Will try and figure out the problem. Spent half an hour but couldn't get anything.

**Comment by mukeshsoni** [comment]
updating `react-elm-components` from 1.0.0 to 1.0.1 did the trick :) who could have thought?

**Comment by mukeshsoni** [comment]
I have published a 2.0.0 version (had to run `apm publish major` twice which weirdly bumped the version twice)

Can anyone try installing it and letting me know if it works for them?
@oli-obk @brunetton @shamansir 

Thanks @shamansir for all the help!
