### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by hakonrossebo** [mukeshsoni/elm-instant#7]
I'm having trouble installing this package (using Windows)

<details>
 <summary>

> npm run install-elm-packages
> cd lib/compilers/elm-compiler/temp && rm -rf elm-stuff && elm-package install -y && cd -
> elm-package: getAppUserDataDirectory: illegal operation (unsupported operation)
> </summary>
> 
> 
> npm run install-elm-packages
> 
> cd lib/compilers/elm-compiler/temp && rm -rf elm-stuff && elm-package install -y && cd -

elm-package: getAppUserDataDirectory: illegal operation (unsupported operation)

npm ERR! Windows_NT 10.0.14931
npm ERR! argv "C:\Users\user.name\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\node.exe" "C:\Users\user.name\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "run" "install-elm-packages"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! elm-instant@0.3.2 install-elm-packages: `cd lib/compilers/elm-compiler/temp && rm -rf elm-stuff && elm-package install -y && cd -`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm-instant@0.3.2 install-elm-packages script 'cd lib/compilers/elm-compiler/temp && rm -rf elm-stuff && elm-package install -y && cd -'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elm-instant package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd lib/compilers/elm-compiler/temp && rm -rf elm-stuff && elm-package install -y && cd -
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elm-instant
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elm-instant
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user.name\AppData\Local\Temp\apm-install-dir-116826-4412-g766qs\node_modules.staging\elm-instant-49807750\npm-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\user.name\AppData\Local\Temp\apm-install-dir-116826-4412-g766qs\package.json'
npm WARN apm-install-dir-116826-4412-g766qs No description
npm WARN apm-install-dir-116826-4412-g766qs No repository field.
npm WARN apm-install-dir-116826-4412-g766qs No README data
npm WARN apm-install-dir-116826-4412-g766qs No license field.
npm ERR! Windows_NT 10.0.14931
npm ERR! argv "C:\Users\user.name\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\node.exe" "C:\Users\user.name\AppData\Local\atom\app-1.10.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\user.name\.atom\.apm\.apmrc" "--userconfig" "C:\Users\user.name\.atom\.apmrc" "install" "C:\Users\user.name\AppData\Local\Temp\d-116826-4412-1dt0if1\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! elm-instant@0.3.2 preinstall: `npm run install-elm-packages`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm-instant@0.3.2 preinstall script 'npm run install-elm-packages'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elm-instant package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run install-elm-packages
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elm-instant
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elm-instant
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user.name\AppData\Local\Temp\apm-install-dir-116826-4412-g766qs\npm-debug.log
</details>

**Comment by mukeshsoni** [comment]
Thanks for reporting. Yeah, all logic for path parsing is assuming a unix type machine. Will try and make it generic but i don't have a windows machine to test.

**Comment by hakonrossebo** [comment]
Ok, just tell me if I should help out testing anything Windows specific.

**Comment by mukeshsoni** [comment]
@hakonrossebo 
Looks like i was wrong. node takes care of interop between unix and windows path separators. This looks like a problem with `elm-package`.

What version of elm are you on? Can you do normal elm-package install in other directories?

**Comment by hakonrossebo** [comment]
I'm using the latest Elm version.  The rm -rf command is different on Windows, it's possible that you need to use the npm rimraf package - https://github.com/isaacs/rimraf. It's also possible that multiple statements on one line, combined with && fails. I could try to verify if I can find some time to look at it.

**Comment by mukeshsoni** [comment]
@hakonrossebo - have pushed your changes in v0.4.4 in the atom package. Can you please try installing from apm and verify?

**Comment by hakonrossebo** [comment]
Thanks - v0.4.4 from apm seems to work fine now.
